export async function GET() {
    return new Response(
      `
      <?xml version="1.0" encoding="UTF-8" ?>
      <urlset
        xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="https://www.w3.org/1999/xhtml"
        xmlns:mobile="https://www.google.com/schemas/sitemap-mobile/1.0"
        xmlns:news="https://www.google.com/schemas/sitemap-news/0.9"
        xmlns:image="https://www.google.com/schemas/sitemap-image/1.1"
        xmlns:video="https://www.google.com/schemas/sitemap-video/1.1"
      >
        <url>
            <loc>https://augstools.vercel.app/</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>1.00</priority>
        </url>
        <url>
            <loc>https://augstools.vercel.app/donate</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://augstools.vercel.app/homebrew</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://augstools.vercel.app/create</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://augstools.vercel.app/assistant</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://augstools.vercel.app/resources</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://augstools.vercel.app/about</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>0.80</priority>
        </url>
        <url>
            <loc>https://augstools.vercel.app/homebrew/heroes</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>0.64</priority>
        </url>
        <url>
            <loc>https://augstools.vercel.app/homebrew/skillcards</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>0.64</priority>
        </url>
        <url>
            <loc>https://augstools.vercel.app/homebrew/heroes/create</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>0.64</priority>
        </url>
        <url>
            <loc>https://augstools.vercel.app/homebrew/skillcards/create</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>0.64</priority>
        </url>
        <url>
            <loc>https://augstools.vercel.app/privacy</loc>
            <lastmod>2023-02-19T19:45:13+00:00</lastmod>
            <priority>0.64</priority>
        </url>
      </urlset>`.trim(),
      {
        headers: {
          'Content-Type': 'application/xml'
        }
      }
    );
  }